### ISSUE TITLE
Odd jshint config comments in source files

### ISSUE THREAD

**Issue by pdehaan** [Floobits/node-fleece#2]
I noticed that this repo uses ESLint (yay!) but there are a bunch of JSHint config comments in the lib/* and tests/* directories:
```js
/*jslint indent: 2, node: true, nomen: true, plusplus: true, todo: true */
```

**Comment by ggreer** [comment]
It's intentional. I need those directives to get my editor's linter to behave. ESLint ignores it, so I guess it's not doing any harm. At some point I'll switch to https://github.com/roadhump/SublimeLinter-eslint, but I'll leave the directives in until then.

**Comment by ggreer** [comment]
I've upgraded to https://github.com/roadhump/SublimeLinter-eslint, so these directives are no longer needed. Thanks for poking me into improving my own dev environment. :)
