### ISSUE TITLE
Convert ./lint.sh into npm script

### ISSUE THREAD

**Issue by pdehaan** [Floobits/node-fleece#3]
Instead of ./lint.sh, you could convert it into an npm script and run it via something like `npm run lint`, where package.json includes:

```js
  "scripts": {
    "test": "NODE_PATH=lib:tests node ./tests/test.js",
    "lint": "eslint lib tests"
  },
```

**Comment by ggreer** [comment]
Sounds good. I'm on it.

**Comment by ggreer** [comment]
Fixed in https://github.com/Floobits/node-fleece/commit/670b288623af8674677076cb8360ab92b7b45aeb
